### ISSUE TITLE
Calculo de quantidade de dias para entrega

### ISSUE THREAD

**Issue by guilhermetb** [lcsbaroni/melhorenvio-magento2#13]
Boa tarde,
Instalei o modulo no magento 2.3 e atendeu totalmente minhas necessidades
Não consegui encontrar para ativar ou configurar quantos dias para o produto ser entregue, como faço pra configurar isso?
Esta outra duvida seria mais especifica, irei trabalhar com dropshipping com fornecedores como hayamax e squidfacil desta forma no parametro de CEP de origem teria que ir o do fornecedor do produto, e possivel configurar ou alterar este atributo?
Desde ja grato,

**Comment by lcsbaroni** [comment]
Boa tarde, na configuração do módulo vc pode definir uma margem para entrega, por exemplo 2 dias que serão adicionados no prazo da transportadora. Tb é possível mapear um atributo do produto e definir essa margem por produto.
No caso de dropshipping ou multi CD ainda não tem uma feature para isso. Pois tem que pensar no caso de um pedido com um produto em cada lugar, como seria esse cálculo.

**Comment by guilhermetb** [comment]
Boa noite, obrigado pelo feedback, a duvida principal é referente a quantos dias o produto sera entregue, esta informação não é exibida quando se calcula o frete.
Em "Text delivery time" você consegue inserir uma mensagem porem não encontrei um parâmetro para sinalizar em quantos dias que a mercadoria será entregue.

**Comment by lcsbaroni** [comment]
Entendi @guilhermetb, é só colocar "%d", por exemplo, " - Em média %d dias úteis"

**Comment by guilhermetb** [comment]
Deu certo aqui! Obrigado!
