### ISSUE TITLE
Problema ao Gerar Label

### ISSUE THREAD

**Issue by ramosl02** [lcsbaroni/melhorenvio-magento2#15]
Estou tentando gerar o Ship atraves do Melhor Envio, nao gera o Label e nao aparece na plataforma do sandbox.melhorenvio.com.br.

Ao criar o Package da o seguinte erro !

"Shipping labels can't be created. Verify that the store information and settings are complete and try again."

Poderia me ajudar ?

**Comment by lcsbaroni** [comment]
Você colocou os dados da sua loja no admin?
Eles sao usados para gerar a etiqueta

**Comment by ramosl02** [comment]
Fiz a configuração e agora apresentou outro erro que gerou LOG

 

[2019-04-19 21:59:34] main.CRITICAL: Notice: Undefined offset: 2 in /mnt/data/home/239072.cloudwaysapps.com/cfffkdynmq/public_html/vendor/lcsbaroni/melhorenvio-magento2/Model/Carrier/MelhorEnvios.php on line 398 {"exception":"[object] (Exception(code: 0): Notice: Undefined offset: 2 in /mnt/data/home/239072.cloudwaysapps.com/cfffkdynmq/public_html/vendor/lcsbaroni/melhorenvio-magento2/Model/Carrier/MelhorEnvios.php on line 398 at /mnt/data/home/239072.cloudwaysapps.com/cfffkdynmq/public_html/vendor/magento/framework/App/ErrorHandler.php:61)"} []

 



 

 

 

Consegue me ajudar ?

 

 

 

De: Luis Baroni <notifications@github.com> 
Enviada em: sexta-feira, 19 de abril de 2019 11:10
Para: lcsbaroni/melhorenvio-magento2 <melhorenvio-magento2@noreply.github.com>
Cc: ramosl02 <luiz.ramos@lprovider.com.br>; Author <author@noreply.github.com>
Assunto: Re: [lcsbaroni/melhorenvio-magento2] Problema ao Gerar Label (#15)

 

Você colocou os dados da sua loja no admin?
Eles sao usados para gerar a etiqueta

**Comment by lcsbaroni** [comment]
Nas configurações de endereço de cliente, você deve utilizar com 4 linhas. O padrão do magento é 2, mas para usar no brasil, o certo é 4. Rua, numero, complemento e bairro.

**Comment by lcsbaroni** [comment]
Conseguiu resolver?

**Comment by ramosl02** [comment]
Luis

 

Não 

Estou com erro ainda na minha plataforma

 

Voce consegue me ajudar ?

 

Esta pegando esse erro !

 

{"0":"The given data was invalid.The to.postal code field is required. (statusCode: 422)","1":"<pre>#1 Lb\\MelhorEnvios\\Service\\v2\\MelhorEnviosService->doRequest('\/api\/v2\/me\/shipm...', array('method' => 'GET', 'data' => array('from' => array('postal_code' => 06220170, 'address' => 'Osasco', 'number' => NULL), 'to' => array('postal_code' => NULL, 'address' => NULL, 'number' => NULL), 'package' => array('weight' => 1, 'width' => 20, 'height' => 20, 'length' => 20), 'options' => array('insurance_value' => 5, 'receipt' => false, 'own_hand' => false, 'collect' => false), 'services' => '1,2,3,4'), 'host' => 'https:\/\/sandbox....')) called at [vendor\/lcsbaroni\/melhorenvio-magento2\/Model\/Carrier\/MelhorEnvios.php:171]\n#2 Lb\\MelhorEnvios\\Model\\Carrier\\MelhorEnvios->collectRates(&Magento\\Quote\\Model\\Quote\\Address\\RateRequest#000000004173501100000000338eb7b6#) called at [vendor\/magento\/module-shipping\/Model\/Shipping.php:305]\n#3 Magento\\Shipping\\Model\\Shipping->collectCarrierRates('melhorenvios', &Magento\\Quote\\Model\\Quote\\Address\\RateRequest#000000004173501100000000338eb7b6#) called at [generated\/code\/Magento\/Shipping\/Model\/Shipping\/Interceptor.php:89]\n#4 Magento\\Shipping\\Model\\Shipping\\Interceptor->collectCarrierRates('melhorenvios', &Magento\\Quote\\Model\\Quote\\Address\\RateRequest#000000004173501100000000338eb7b6#) called at [vendor\/magento\/module-shipping\/Model\/Shipping.php:221]\n#5 Magento\\Shipping\\Model\\Shipping->collectRates(&Magento\\Quote\\Model\\Quote\\Address\\RateRequest#000000004173501100000000338eb7b6#) called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#6 Magento\\Shipping\\Model\\Shipping\\Interceptor->___callParent('collectRates', array(&Magento\\Quote\\Model\\Quote\\Address\\RateRequest#000000004173501100000000338eb7b6#)) called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#7 Magento\\Shipping\\Model\\Shipping\\Interceptor->Magento\\Framework\\Interception\\{closure}(&Magento\\Quote\\Model\\Quote\\Address\\RateRequest#000000004173501100000000338eb7b6#) called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#8 Magento\\Shipping\\Model\\Shipping\\Interceptor->___callPlugins('collectRates', array(&Magento\\Quote\\Model\\Quote\\Address\\RateRequest#000000004173501100000000338eb7b6#), array(array('temando-shipping...'))) called at [generated\/code\/Magento\/Shipping\/Model\/Shipping\/Interceptor.php:78]\n#9 Magento\\Shipping\\Model\\Shipping\\Interceptor->collectRates(&Magento\\Quote\\Model\\Quote\\Address\\RateRequest#000000004173501100000000338eb7b6#) called at [vendor\/magento\/module-quote\/Model\/Quote\/Address.php:1024]\n#10 Magento\\Quote\\Model\\Quote\\Address->requestShippingRates() called at [vendor\/magento\/module-quote\/Model\/Quote\/Address.php:958]\n#11 Magento\\Quote\\Model\\Quote\\Address->collectShippingRates() called at [vendor\/magento\/module-quote\/Model\/Quote\/Address\/Total\/Shipping.php:81]\n#12 Magento\\Quote\\Model\\Quote\\Address\\Total\\Shipping->collect(&Magento\\Quote\\Model\\Quote\\Interceptor#00000000417352af00000000338eb7b6#, &Magento\\Quote\\Model\\ShippingAssignment#000000004173507900000000338eb7b6#, &Magento\\Quote\\Model\\Quote\\Address\\Total#000000004173506e00000000338eb7b6#) called at [vendor\/magento\/module-quote\/Model\/Quote\/TotalsCollector.php:274]\n#13 Magento\\Quote\\Model\\Quote\\TotalsCollector->collectAddressTotals(&Magento\\Quote\\Model\\Quote\\Interceptor#00000000417352af00000000338eb7b6#, &Magento\\Quote\\Model\\Quote\\Address#00000000417353ff00000000338eb7b6#) called at [app\/code\/Mageplaza\/Osc\/Controller\/Index\/Index.php:94]\n#14 Mageplaza\\Osc\\Controller\\Index\\Index->initDefaultMethods(&Magento\\Quote\\Model\\Quote\\Interceptor#00000000417352af00000000338eb7b6#) called at [generated\/code\/Mageplaza\/Osc\/Controller\/Index\/Index\/Interceptor.php:37]\n#15 Mageplaza\\Osc\\Controller\\Index\\Index\\Interceptor->initDefaultMethods(&Magento\\Quote\\Model\\Quote\\Interceptor#00000000417352af00000000338eb7b6#) called at [app\/code\/Mageplaza\/Osc\/Controller\/Index\/Index.php:58]\n#16 Mageplaza\\Osc\\Controller\\Index\\Index->execute() called at [generated\/code\/Mageplaza\/Osc\/Controller\/Index\/Index\/Interceptor.php:24]\n#17 Mageplaza\\Osc\\Controller\\Index\\Index\\Interceptor->execute() called at [vendor\/magento\/framework\/App\/Action\/Action.php:108]\n#18 Magento\\Framework\\App\\Action\\Action->dispatch(&Magento\\Framework\\App\\Request\\Http#00000000417356ca00000000338eb7b6#) called at [vendor\/magento\/module-checkout\/Controller\/Onepage.php:161]\n#19 Magento\\Checkout\\Controller\\Onepage->dispatch(&Magento\\Framework\\App\\Request\\Http#00000000417356ca00000000338eb7b6#) called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#20 Mageplaza\\Osc\\Controller\\Index\\Index\\Interceptor->___callParent('dispatch', array(&Magento\\Framework\\App\\Request\\Http#00000000417356ca00000000338eb7b6#)) called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#21 Mageplaza\\Osc\\Controller\\Index\\Index\\Interceptor->Magento\\Framework\\Interception\\{closure}(&Magento\\Framework\\App\\Request\\Http#00000000417356ca00000000338eb7b6#) called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#22 Mageplaza\\Osc\\Controller\\Index\\Index\\Interceptor->___callPlugins('dispatch', array(&Magento\\Framework\\App\\Request\\Http#00000000417356ca00000000338eb7b6#), array(array('designLoader', 'customerNotifica...', 'catalog_app_acti...', 'tax-app-action-d...', 'weee-app-action-...', 'storeCheck', 'contextPlugin', 'customer-app-act...'))) called at [generated\/code\/Mageplaza\/Osc\/Controller\/Index\/Index\/Interceptor.php:78]\n#23 Mageplaza\\Osc\\Controller\\Index\\Index\\Interceptor->dispatch(&Magento\\Framework\\App\\Request\\Http#00000000417356ca00000000338eb7b6#) called at [vendor\/magento\/framework\/App\/FrontController.php:159]\n#24 Magento\\Framework\\App\\FrontController->processRequest(&Magento\\Framework\\App\\Request\\Http#00000000417356ca00000000338eb7b6#, &Mageplaza\\Osc\\Controller\\Index\\Index\\Interceptor#00000000417354b900000000338eb7b6#) called at [vendor\/magento\/framework\/App\/FrontController.php:99]\n#25 Magento\\Framework\\App\\FrontController->dispatch(&Magento\\Framework\\App\\Request\\Http#00000000417356ca00000000338eb7b6#) called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#26 Magento\\Framework\\App\\FrontController\\Interceptor->___callParent('dispatch', array(&Magento\\Framework\\App\\Request\\Http#00000000417356ca00000000338eb7b6#)) called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#27 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(&Magento\\Framework\\App\\Request\\Http#00000000417356ca00000000338eb7b6#) called at [vendor\/magento\/module-store\/App\/FrontController\/Plugin\/RequestPreprocessor.php:94]\n#28 Magento\\Store\\App\\FrontController\\Plugin\\RequestPreprocessor->aroundDispatch(&Magento\\Framework\\App\\FrontController\\Interceptor#000000004173573d00000000338eb7b6#, &Closure#00000000417357d200000000338eb7b6#, &Magento\\Framework\\App\\Request\\Http#00000000417356ca00000000338eb7b6#) called at [vendor\/magento\/framework\/Interception\/Interceptor.php:135]\n#29 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(&Magento\\Framework\\App\\Request\\Http#00000000417356ca00000000338eb7b6#) called at [vendor\/magento\/module-page-cache\/Model\/App\/FrontController\/BuiltinPlugin.php:69]\n#30 Magento\\PageCache\\Model\\App\\FrontController\\BuiltinPlugin->aroundDispatch(&Magento\\Framework\\App\\FrontController\\Interceptor#000000004173573d00000000338eb7b6#, &Closure#00000000417357d200000000338eb7b6#, &Magento\\Framework\\App\\Request\\Http#00000000417356ca00000000338eb7b6#) called at [vendor\/magento\/framework\/Interception\/Interceptor.php:135]\n#31 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(&Magento\\Framework\\App\\Request\\Http#00000000417356ca00000000338eb7b6#) called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#32 Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins('dispatch', array(&Magento\\Framework\\App\\Request\\Http#00000000417356ca00000000338eb7b6#), NULL) called at [generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php:26]\n#33 Magento\\Framework\\App\\FrontController\\Interceptor->dispatch(&Magento\\Framework\\App\\Request\\Http#00000000417356ca00000000338eb7b6#) called at [vendor\/magento\/framework\/App\/Http.php:136]\n#34 Magento\\Framework\\App\\Http->launch() called at [generated\/code\/Magento\/Framework\/App\/Http\/Interceptor.php:24]\n#35 Magento\\Framework\\App\\Http\\Interceptor->launch() called at [vendor\/magento\/framework\/App\/Bootstrap.php:258]\n#36 Magento\\Framework\\App\\Bootstrap->run(&Magento\\Framework\\App\\Http\\Interceptor#000000004173568c00000000338eb7b6#) called at [index.php:39]\n<\/pre>","url":"\/onestepcheckout\/","script_name":"\/index.php"}

 

 

 

De: Luis Baroni <notifications@github.com> 
Enviada em: sexta-feira, 24 de maio de 2019 15:57
Para: lcsbaroni/melhorenvio-magento2 <melhorenvio-magento2@noreply.github.com>
Cc: ramosl02 <luiz.ramos@lprovider.com.br>; Author <author@noreply.github.com>
Assunto: Re: [lcsbaroni/melhorenvio-magento2] Problema ao Gerar Label (#15)

 

Conseguiu resolver?

**Comment by lcsbaroni** [comment]
vc pode ver no log que o CEP de destino está nulo. Você precisa ver o porque não está passando o CEP. Verifique o nome dos campos que vc está usando.
No calculo ele usa essas informações:
`"to" => [
                "postal_code" => $request->getDestPostcode(),
                "address" => $request->getDestRegionCode(),
                "number" => $request->getDestRegionId()`
