### ISSUE TITLE
Problema ao calcular o frete

### ISSUE THREAD

**Issue by guilhermetb** [lcsbaroni/melhorenvio-magento2#17]
Boa noite,
Estou utilizando o módulo e venho enfrentado problemas para realizar o calculo no checkout.
No checkout digito o CEP e o modulo não entra automatico calculando, preciso apertar F5 para dar um refresh na pagina e neste momento o frete é calculado.
No carrinho ou no calculo de frete na pagina do produto funciona corretamente.
Alguem pode me ajudar?

**Comment by lcsbaroni** [comment]
Você já viu nos logs se acontece algum erro? Qual versão você está utilizando?

**Comment by guilhermetb** [comment]
Versão que estou utilizando do módulo:
==================================================================
name     : lcsbaroni/melhorenvio-magento2
descrip. : Modulo melhor envios magento 2
keywords :
versions : * 0.4.2
type     : magento2-module
path     : /var/www/html/magento2/vendor/lcsbaroni/melhorenvio-magento2
names    : lcsbaroni/melhorenvio-magento2

autoload
files
psr-4
Lb\MelhorEnvios\ => .

requires
php >=7.0

requires (dev)
friendsofphp/php-cs-fixer ^2.14
phpunit/phpunit ^7.5
==================================================================

O problema estava ocorrendo devido a um problema no checkout do magento2, consegui resolver aplicando uma solução alternativa.
