### ISSUE TITLE
Erro ao buscar as Agencias Jadlog

### ISSUE THREAD

**Issue by danielbohnrs** [lcsbaroni/melhorenvio-magento2#18]
Olá,
Quando ainda não foi configurado o token do Melhor Envios, dá erro ao entrar na configuração dos métodos de envio (pois tenta usar o token na criação do serviço pra consultar as Agencias Jadlog, mesmo não precisando do token nessa hora):
`Fatal error: Uncaught TypeError: Argument 1 passed to Lb\MelhorEnvios\Service\v2\MelhorEnviosService::__construct() must be of the type string, null given, called in /opt/bitnami/apache2/htdocs/app/code/Lb/MelhorEnvios/Model/System/Config/Source/AgencyJadlog.php on line 83 and defined in /opt/bitnami/apache2/htdocs/app/code/Lb/MelhorEnvios/Service/v2/MelhorEnviosService.php:39 Stack trace: #0 /opt/bitnami/apache2/htdocs/app/code/Lb/MelhorEnvios/Model/System/Config/Source/AgencyJadlog.php(83): Lb\MelhorEnvios\Service\v2\MelhorEnviosService->__construct(NULL, 'sandbox', Object(Magento\Framework\Logger\Monolog)) #1 /opt/bitnami/apache2/htdocs/app/code/Lb/MelhorEnvios/Model/System/Config/Source/AgencyJadlog.php(53): Lb\MelhorEnvios\Model\System\Config\Source\AgencyJadlog->getService() #2 /opt/bitnami/apache2/htdocs/vendor/magento/module-config/Model/Config/Structure/Element/Field.php(458): Lb\MelhorEnvios\Model\System\Config\Source\AgencyJadlog->toOptionArray(false) #3 /opt/bitnami/apache2/htdocs/vendor/magento/module-config/ in /opt/bitnami/apache2/htdocs/app/code/Lb/MelhorEnvios/Service/v2/MelhorEnviosService.php on line 39`

O erro não acontece quando se tem uma versão anterior do módulo já configurada e aí atualiza, pois neste caso o token já está configurado.

**Comment by lcsbaroni** [comment]
Qual versão você testou? Isso foi corrigido na ultima release 0.4.2

**Comment by danielbohnrs** [comment]
Testei com a versão que está na branch Master. 0.4.1, pelo que vi.
Vou testar com a 0.4.2 então.
Obrigado

**Comment by danielbohnrs** [comment]
Mesmo baixando pelo https://github.com/lcsbaroni/melhorenvio-magento2/archive/0.4.2.zip
no arquivo module.xml continua com a versão 0.4.1 (tentei também com `git clone httsp://github.com/lcsbaroni/melhorenvio-magento2.git --branch 0.4.2` )
Como que devo proceder para baixar a versão 0.4.2 corretamente?

**Comment by lcsbaroni** [comment]
Estranho, vc pode ver que está correto o arquivo na tag 0.4.2 https://github.com/lcsbaroni/melhorenvio-magento2/blob/0.4.2/etc/config.xml. Vc limpou o var e o cache? Como o default fica no xml, vc precisa limpar o diretório

**Comment by danielbohnrs** [comment]
Acredito que apenas tenha faltado atualizar a versão no arquivo https://github.com/lcsbaroni/melhorenvio-magento2/blob/0.4.2/etc/module.xml
Pois no último commit foi colocado a versão 0.4.2 apenas no composer.json e não no arquivo módule.xml.

**Comment by danielbohnrs** [comment]
De qualquer forma, não tive mais problemas com isso.

**Comment by lcsbaroni** [comment]
Que bom! Vou fechar a issue.
