### ISSUE TITLE
Erro ao comprar etiquetas com transportadora Jadlog

### ISSUE THREAD

**Issue by danielbohnrs** [lcsbaroni/melhorenvio-magento2#22]
Nos meus testes, quando tento criar as etiquetas de envio, para Jadlog, recebo  o seguinte erro:
`Esta transportadora não aceita envios não-comerciais partindo deste estado` (testei com várias agências diferentes)

Pelo que vi no módulo está fixo
` "non_commercial" => true`
esta configuração não deveria ser padrão 'false', já que teoricamente num e-commerce todos os envios são comerciais?
Ou pelo menos ter alguma forma de configurar todos os campos (non_commercial, collect, reverse atualmente são fixos)  como os 'receipt' e 'own_hand' já são

**Comment by danielbohnrs** [comment]
Fiz um teste trocando para `"non_commercial" => false` aí o erro é: `A nota fiscal é obrigatória para esta transportadora  em envios comerciais`. 

```
   "invoice": { // nota fiscal (opcional se for Correios)
      "number": "12345", // número da nota
      "key": "nf-e" // chave da nf-e
    },
```


Há alguma forma de usar Jadlog da forma que está agora o módulo?

**Comment by lcsbaroni** [comment]
Essa parte de nota fiscal não foi implementada ainda. Por isso está fixo. Se vc estiver implementando essa parte, por favor, abre um PR para colocar em uma versão.
